---
linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # use "github.com/pkg/errors" instead
      - errors
      # use "github.com/golang/protobuf/proto" instead
      - github.com/gogo/protobuf/proto
      # use "github.com/percona-platform/saas" instead
      - github.com/percona-platform/platform

  goimports:
    local-prefixes: github.com/percona/pmm-managed

  lll:
    line-length: 170
    tab-width: 4

  unused:
    check-exported: true

  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - exhaustivestruct  # useless
    - gochecknoglobals  # mostly useless
    - goerr113          # we use different approach for errors
    - gomnd             # we are using numbers in many cases
    - gomodguard        # we are not using modules
    - nlreturn          # too annoying
    - scopelint         # too many false positives
    - wsl               # too annoying

issues:
  exclude-use-default: false
  exclude:
    - 'G104: Errors unhandled'                   # gas: duplicated errcheck checks
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen         # tests may be long
        - unused         # very annoying false positive: https://github.com/golangci/golangci-lint/issues/791
        - testpackage    # senseless
