dist: bionic
language: go

services:
  - docker

go:
  - 1.12.x
  - 1.13.x
  # - TODO master

matrix:
  fast_finish: true
  allow_failures:
    - go: master

# skip non-trunk PMM-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{4}/

cache:
  directories:
    - /home/travis/.cache/go-build
    # - /home/travis/gopath/pkg

before_cache:
  - go clean -testcache
  # - go clean -cache

env:
  global:
    - CODECOV_ENV=PROMETHEUS_IMAGE,GRAFANA_IMAGE,POSTGRES_IMAGE,PMM_SERVER_IMAGE

    # there is no case when pmm-update is older than pmm-managed (pmm-update self-updates first),
    # so there is no need to test with old PMM Server versions
    - PMM_SERVER_IMAGE=perconalab/pmm-server:dev-latest

    # TODO https://jira.percona.com/browse/PMM-1772
    # AWS - PMM Autotest account. TODO https://jira.percona.com/browse/PMM-4896
    # Travis secrets are not exposed to pull requests from forks: https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions
    # - AWS_ACCESS_KEY=AKIAZPBRO3QWINUW4BHY
    # - secure: "IVxN/Afvz3K/yyUVLgUenF5lVdbdzdajgsiWINOr7oR8YpkCd/7Ns/0FAOCbXw4hhxQr14Lx9oUJUrF2pbK/ImJFSLS0Ro9jiW+MdcEWs6ScshGSfM/DslDFDgpYumRiRIpzrtjODIPoQ15BDjQwu8b2yXOzgJhrGe01cRe5wUIrljW7sdBn0T3uq28aZ2PhieI22BNTN2D9SPnXho9ioekfYtDlgS8B7NcbKyJq9r9zQJc/eOXaBGkTxfReXQtbwjFHBG6XHib7CQyPA8LVpWqfE+dwye7ySDqenGxp9OXlJ7+lofJytAwMdX0MZ40z4SygXIDdMaIiN+FSS/NOhSTFHkeEgrDGnWBr4WC+ygUsm17RGEO6wQ1/Bjzx7VuMGccwnGgnDkx+l2/WNZs8tGhfznG+s+YGpgVuiU/X1GJU+XqWhvzicfWVt5iQWR7IKG0W+vesVvnA46LS262sbduprjreyeZJghHWAEFXGNnbgxlknQVS0+dh0t0y1ncAvJK4hhWmTU7D2o1niN21Y7MBCQDDKHoprPdHMFN9CxEdqr+ICO4QHcAGGs5dZLUzxY4brBMli6AqlPAC8rS4c1fHS24OFI5jaiB5bZaVWI1Ust5TEMaSikdXtANxm5HTcM9MXcrAfb7goteULSsmPQ0Y1S6I57+zpo4JB2zFcts="
    # - AWS_RDS_USERNAME=b6xtHlZ6Fjop
    # - secure: "AbMg5No12vxv/ZWkhFEeMngsQ9nJeoqunmLhUfW8B4yy8YjAqZfG/pIG24cWVzqZs9mVSQOzJGlVsSmlvKk1EokJG1DCUya71cpPfPlKybZGS7WePMz26w5Ns/NJjEYAixa55SstOctZKm7pnwFJASky5knZahnOCpm5/Oo5BfSrz1M19g8AQkt5lV5X2GnLqesHzlXW2d62xTHiqLK3+w+6x6TIYJQ/KHpbMXkq2oGwRpjzxcPuFQez4cUeNoPtw8k4XWAYhhdYnIZf0kJBt9xbbz5b2kCbdamcZ3rQFp6cvnu3qjAkyx7kXF3aNQym38ZfbJuDm/e1tA2k5vzpzFZKn9o5xKOOG1x2nyoDMpKN+jBXExSQbdAO7n9C1K+ZJc85vtisW7h3ZB12u0gDH0/zE+8Cxf40aQWXeGL48PmfFpV0QKpdedg4U2hh4xWs4lEJT2iW+fT25ruo0RLO2A4wRkhugIkPvjGVEdQLeZBr7r9Ht+TEwFZtl/8DqQJXE7xRzvXy5cbcVxNw0u3qzxrBWhHQcYQzzD+rT4cFlQnuVpPQ94upF5/HEK1fEUW8pBafdxb3JzciZff88ZRhVcIPjsFjIu9oKoj34MhkKgoBQ7SojTVRDjY/wTsu19GcVylk6798vG+p9X0yP4IMH6kcx9EMhSrJx3jFJFi2RkM="

  matrix:
    # what we currently use in PMM
    - PROMETHEUS_IMAGE=prom/prometheus:v2.12.0
      GRAFANA_IMAGE=grafana/grafana:6.4.4
      POSTGRES_IMAGE=postgres:11.5

    # latest released version
    - PROMETHEUS_IMAGE=prom/prometheus:latest
      GRAFANA_IMAGE=grafana/grafana:latest
      POSTGRES_IMAGE=postgres:latest

    # current master
    - PROMETHEUS_IMAGE=prom/prometheus:master
      GRAFANA_IMAGE=grafana/grafana:master
      POSTGRES_IMAGE=postgres:latest

before_install:
  - docker-compose up -d
  - docker exec pmm-managed-server /root/go/src/github.com/percona/pmm-managed/.devcontainer/install-dev-tools.sh

install:
  # ensure that vendor/ is in sync with code and Gopkg.toml/lock
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep check

before_script:
  # ensure that generated files are not changed
  - make init
  - make gen
  - make format
  - git status
  - git diff --exit-code

script:
  # for main_test.go
  - make install

  - make test-race
  - make test-cover
  - make test-crosscover

  - make devcontainer TARGET=test-race-crosscover \
                      TEST_FLAGS='-timeout=180s -v' \
                      TEST_PACKAGES=./services/supervisord \
                      TEST_RUN_UPDATE=1

  - make check

after_success:
  - curl https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f race-crosscover.out -F devcontainer,crosscover -X fix
  - ./codecov -f cover.out -F normal,cover -X fix
  - ./codecov -f crosscover.out -F normal,crosscover -X fix

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: QDKp28RJiVnst5gGKSKhVWvyIacYFLvl4eypPQoagrUm7VlQlGdmExH841OtURbqwNNsQoai2kP1XfxxSTPtTzmp6rMsBH4D4+cAfpqE2xgP/zQ1ctbA7B4hSAGu0FkAzyhiQb6HaGIeELaTiS5uTgwHn64BNgNtf8rC3mCIUanKlpAwPOejDOvldjkL3TzNkjnv9kujLQhiSSlldMownb0gNeSiH2HfYAZ9XT5wQj6rBEGI2Mk5xBzkEduLpHMe6r8Ocko3j3q3czrNrlrqgPiTzYIh+A1h6cSGu4xe6C3WmANVbHi/ieeM3YM+pT1ff5Mx0g75Kyi18zBCSWL4tBOeu+ciHPAPKFGx7sv5ivLNzoKJm/Fc3AsdkkAvSHErsrRCWdwemRveSdbNOkwDybNSso3ERRZ8YuWIP5rdKb8HIprVuMrvlrpjXi5p901Nabt7Pw4mgDBVJIIvZn8PJ4N/0T+RGO2bV38JlWIutLFHFcHcQ2QPZOiGPffxbtfmU7x7+J4QCHhA4ucYkwzxEb7UZcGpSxz3+zVoP25c480Z56KInkxIEi0LBEqw2s7MqsKpgho4KJIpCbciDhPN7MTm4aVeYjtJ0GgIbgKXuaLWMUMcYQ0yTHUHweGMHLSF/k7cdP8WSb4z1LtJqxKzye9IcejdacVPhdLzHaprW7w=
