dist: trusty
sudo: required
language: go

go:
  - 1.9.x
  - master

matrix:
  allow_failures:
    - go: master

env:
  global:
    # AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY
    # They are not exposed for external pull requests: https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions
    - secure: WPLGcwEg9yZ6UwnR87zLLtZzxlJPg+UaqnNWpFeFpIi3qm00jFtHumf4mOVt+VvyoSFQ4fVSeja16QVcov1s2M+tTdC27nxKpKmeuq5qBIyTUhcTjCSFGRmgqclw6JDpE3DuLqv0o4aqXNboziEXPDdnf4KlrVsLsVvdE8Vx67W5qpaks1asiah7EDRFZQgibVPgRVHrroUijx3YpA23HSyhJH/6Yhyf05MdT5y3l9NhbHgBzdTSoq4tKJKsAxiuyDg3mHl496+Ab72qyVq5Ph9zWFfk4lm9MlmBiRQmiZgESaXKI0JkZo9riBn4MM5YvaJN05DRWPSuQmrQx3H0DAe0VPWl6k5V85dvC0QbnHAXbffFQH/8J7VvxsHENjwwQJ24USFCtjF7QMVgSzSVQtK+dVpiChAOs/tSRtGDYCffKt/tfIjJEvgSHfV9LgIId03EezBCTfZoL/TvsiV2uZ/tN3tONPkbekVobFTSi/vJsI57QG3x1IiKyq1JuxQxAE2Y75Y8h9mNNDRIjFcAIOYr2vZZfVvuC7Ba9cSwvjzSI89xDnC7OPP1x9+dWWvmF1/4ZXpAmnjcnhP0l4GhEbsE/PvdGsiqDtK5rrzpGK9WiD3EO5oJN3yOL9LZ99evzxd+coFnTr1PggEbVEbnwYgiDDExUxb0DYiw8sMdFKM=
    - secure: EabYo1jrgHLJvsiopDkvShz7ou7z6TBn4Wj7uEpWYmg20wCOXrBLq8Gzed09cRcJaOb7CHFeLTU5qffwH6yJR/NH9l1XqDzWXZZU++C/Kkgwma9EJI7ytqJ5ANh7CSXGGbGB5urRlyh09FJj+4QOBrG1cBW5McD6OPtLSLRVuD7qvJIwgAtLhkgNBBEM3A/Q3RHGNPwdEHxwt5nJBt/Kpc31xUtLYUsZ5dS55KS0WKFf2gUOO5FZVZFPL2dVSb00nn6dafAG2zFHq+HTp08MeyFa3/++Isvu1OKxbAqKPDGI3JqkyZXDb8ZMECzzomdHUJwxwHLJSzOBMm5NEFbav9K2g0Ko9IQamYJBinGoqXMRTL/RCCO80uEJRaT0Gn14RBelM89oR2uyvbZSDm763Myz957UjjxcZCYDs8dZNnmZTk35gbm1Dlt45DPRCroMOIiN3LU8dE96J5uxHrJu7fwABn7xQPrJbsrmSKQPtvc9/mLhwRJGXlQrG26BJJfXtkN8FY9JgRpY3WjKSlvEiKjFTGSLgB9XtUywGvXjtQWRB7/oas0TCfsaf1baZzYAV0TkOGN9Ya7+9LdgqzvdKFN+M2FmHFq/cPQy/I++jMFdAz+Z8EVu55K+0Eq+bldWDKkHV1R5mimSImb0aBeWVzmzfLHEl0FyduKc3pOnUjI=
    - MYSQL_IMAGE=percona/percona-server:5.7

  matrix:
    - PROMETHEUS_IMAGE=prom/prometheus:v1.8.2
      ALERTMANAGER_IMAGE=prom/alertmanager:v0.9.1
      CONSUL_IMAGE=consul:0.9.3
    # TODO
    # - PROMETHEUS_IMAGE=prom/prometheus:master
    #   ALERTMANAGER_IMAGE=prom/alertmanager:master
    #   CONSUL_IMAGE=consul:latest

before_install:
  # no package for Trusty yet
  # - sudo add-apt-repository -y ppa:maarten-fonville/protobuf
  # - sudo apt-get -qq update
  # - sudo apt-get install -y protobuf

  # install protoc the hard way
  # - git clone --depth 1 --branch v3.3.2 https://github.com/google/protobuf /tmp/protobuf
  # - cd /tmp/protobuf
  # - ./autogen.sh
  # - ./configure
  # - make -j2
  # - sudo make install
  # - sudo ldconfig

  # install compiled release
  - wget https://github.com/google/protobuf/releases/download/v3.4.0/protoc-3.4.0-linux-x86_64.zip
  - unzip -q protoc-3.4.0-linux-x86_64.zip
  - sudo install -d /usr/local/include/google/protobuf/compiler
  - sudo install -m 755 bin/protoc /usr/local/bin/
  - sudo install -m 644 include/google/protobuf/*.proto /usr/local/include/google/protobuf/
  - sudo install -m 644 include/google/protobuf/compiler/*.proto /usr/local/include/google/protobuf/compiler/

  - protoc --version

script:
  - sudo service mysql stop
  - docker-compose up -d

  # check that generated files are not changed
  - make init gen
  - git diff --exit-code

  - make cover

after_success:
  - bash <(curl -s https://codecov.io/bash) -X fix

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: QDKp28RJiVnst5gGKSKhVWvyIacYFLvl4eypPQoagrUm7VlQlGdmExH841OtURbqwNNsQoai2kP1XfxxSTPtTzmp6rMsBH4D4+cAfpqE2xgP/zQ1ctbA7B4hSAGu0FkAzyhiQb6HaGIeELaTiS5uTgwHn64BNgNtf8rC3mCIUanKlpAwPOejDOvldjkL3TzNkjnv9kujLQhiSSlldMownb0gNeSiH2HfYAZ9XT5wQj6rBEGI2Mk5xBzkEduLpHMe6r8Ocko3j3q3czrNrlrqgPiTzYIh+A1h6cSGu4xe6C3WmANVbHi/ieeM3YM+pT1ff5Mx0g75Kyi18zBCSWL4tBOeu+ciHPAPKFGx7sv5ivLNzoKJm/Fc3AsdkkAvSHErsrRCWdwemRveSdbNOkwDybNSso3ERRZ8YuWIP5rdKb8HIprVuMrvlrpjXi5p901Nabt7Pw4mgDBVJIIvZn8PJ4N/0T+RGO2bV38JlWIutLFHFcHcQ2QPZOiGPffxbtfmU7x7+J4QCHhA4ucYkwzxEb7UZcGpSxz3+zVoP25c480Z56KInkxIEi0LBEqw2s7MqsKpgho4KJIpCbciDhPN7MTm4aVeYjtJ0GgIbgKXuaLWMUMcYQ0yTHUHweGMHLSF/k7cdP8WSb4z1LtJqxKzye9IcejdacVPhdLzHaprW7w=
