dist: bionic
language: go

services:
  - docker

go:
  - 1.13.x
  # - master

matrix:
  fast_finish: true
  allow_failures:
    - go: master

# skip non-trunk PMM-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{4}/

cache:
  directories:
    - /home/travis/.cache/go-build
    # - /home/travis/gopath/pkg

before_cache:
  - go clean -testcache
  # - go clean -cache

go_import_path: github.com/percona/pmm-managed

env:
  global:
    - CODECOV_ENV=PROMETHEUS_IMAGE,GRAFANA_IMAGE,POSTGRES_IMAGE,PMM_SERVER_IMAGE

    # there is no case when pmm-update is older than pmm-managed (pmm-update self-updates first),
    # so there is no need to test with old PMM Server versions
    - PMM_SERVER_IMAGE=perconalab/pmm-server:dev-latest

    # AWS - PMM Autotest account.
    # Travis secrets are not exposed to pull requests from forks: https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions
    - AWS_ACCESS_KEY=AKIAZPBRO3QWGCO72MJZ
    # AWS_SECRET_KEY
    - secure: "NtO5BJJKVMkKrZ1AGIHzBrIvHb1sYlQUa2PBGrB5YJZaQbzYFFdxZdI5AizWBFOVmSmgy/zbb4TmETvObJj7RXwDIu0Kzkuqtv4/NKG8VJIAvKHdOTSb4O8wXb4GkoVVcFaqcU9tEP/9lOtCYZdC2ILWTUJmPf7rCQ+DVTc8Iy0987ClS3rS0eg/DL/SgZ8lIHNAaOqH+ICM09ScSwk6ENyWLA4o637OSfcsejOoHSxiTkNtcZo/VHebVwnT8HHyB8RSw6DLyS7pTzqkSckp0WnCnIKSrY05w9jIQV54RyFrPo7UQ07tx8cD6jXCriePC4H1G9NAwclYYrMfB5IWRhmCUZ7wgR+QEK4ZgF6B8GW1roG/T97smHzaxjLWyGMK7Xd8kYkqJaS1cuIfIoCbpTWJ7AWBPbi/mIhfqIKvc+XtGJEj0ur2lG6AOkI5K7Lu7qmwXUKRtrc382XFe9dPT7Guq/OVl7Zgdg0QKsKlD8ndSWRoKZz0SBkpSveeJksq32Q1NAOgHeXGvln4AY9WFEqUMOejc2F1IOytGmHS6Df0JVhke0mLAUtoOs1b+gV5EtN0qu5/JN3kUvY9v92kpOgF0rZafhWTFXM32PnxExMiVdjHI+Hh1SHNumhUaGLqnUEaqDX3hGQW0t2RamW5zqhpFdgoSpqKCDZWht6d7xw="
    # AWS_RDS_USERNAME
    - secure: "VB+UW41dd2remOq2szBrhXdK5/GA+/qUk2Pnc8JEdwgxFiyjCCDa+JB7HXlfRODPZvNJAL8KwG/YY4pxt0vbZ0/zQs/O39UsBT9tZdX5s/+zHEF75z+cVvB1R8MrxcD2B0zlMQNK/ezmXk/SZOOrtsCsCj9mIrDBsZlNAdh4RNfIVJVc6mREhuObLYODRm0w+d0cYL7jJilhRG0mHfvfCXSlHof1yv1p6l+7nrJP66MgjJrEthzLUerig9WkQp7v3TFCUADIlQxHrNz7Z1V1C2r6YQrfOYi9qVMWu4PUQL5pvAjOw/e/T7SvGKnuPBAybOYHz88wzY79j5KyCwlBYy91SKw3DB0+NklAwYnhbW0NyDrLdU5g9xSCgp+7tGv4YE7rMDxrF683zeGqx8bZLb9cY+wQQBbYi/2Pq2j53tS04O31Q7LePdk1r8odcyYiUUFkFQt7tBRRQSMbEIr4n36DzDUyqX4OofBbsVRSjkFbjZVfv7HvJRha5jQwNqgZ4fWwIbL6N7M9LoxvDk4H3QHRH4y37AcjQfhNM56jnZbtWErNhRikzsFwMmcga4hbDjSzD/+luq/K2QeQdWtIXUtwiZo8r5xfTk1/DMMuLNiddH1oagIrCRXGAMgvuzGmEfCEBFJKU6u2WfdpMggaLCX3pA5CiXT0pzg16e8MYJo="
    # AWS_RDS_PASSWORD
    - secure: "iVVToSZWmR+9Y8mXVKiWl2p0mfS9hAQxW5dAeNlXQk9ara/2cvmdffOmLLGkhI5caZvQSVjne5enkng1Y6Ifns+heuhqiPS8495eds+PKl/70YNUgoIOXUWEehimHnNLg6R9q7uxrqy8rql89LAXZaeJImVnRrm0LoZ9jgVYivCqUpUcUxJ3CsFkZwJv5LSAFI964DaG2rsj2fiNixx6tnUAssQMGpoWoo9o+psb4Uwyr8S1rABCiMt494iw7RenlhCIFv2O04+p305Nx8wy11n9tV1ViK7tKF819Lw/iXB+5DA4CrT+ff56EdPWJ4wik7CEtydKcjAx0C00s04H93GuGoyWqFLFNliNj54d8BtRu0YZBhl9m51N3dPxq+usTrdV/veL0IJ7pNqK3CV+IKc9Qb+xHNuuYgcZaMMKKaB4+5TQR/pCe+i9v3shJW+zXUWsv0WS2zTIabZNWHNlTb9aPTyHPSyf9CbB04qFa4mcza/ohhhA6pCin9ZScHCtb45DHPMe6/khQIztkuyTwBWpLWYEjnbeOjOFgRKf1Zt2AYi8yR6Vcv9gDxrYu+KOqIuqKpS7Yn1Fcktsn7ty/rTr6XWlmhg3TLKRG6C2kTNNwxJmBo4WPcsENeuS5JQjsXp46ZWFeC4VsLZe7p62bM4QjtECqWX1I5rtiCShKIc="

  matrix:
    # what we currently use in PMM
    - PROMETHEUS_IMAGE=prom/prometheus:v2.12.0
      GRAFANA_IMAGE=grafana/grafana:6.4.4
      POSTGRES_IMAGE=postgres:11.5

    # latest released version
    - PROMETHEUS_IMAGE=prom/prometheus:latest
      GRAFANA_IMAGE=grafana/grafana:latest
      POSTGRES_IMAGE=postgres:latest

    # current master
    - PROMETHEUS_IMAGE=prom/prometheus:master
      GRAFANA_IMAGE=grafana/grafana:master
      POSTGRES_IMAGE=postgres:latest

before_install:
  - docker-compose up -d
  - docker exec pmm-managed-server /root/go/src/github.com/percona/pmm-managed/.devcontainer/install-dev-tools.sh

install:
  # ensure that vendor/ is in sync with code and Gopkg.toml/lock
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep check

before_script:
  # ensure that generated files are not changed
  - make init
  - make gen
  - make format
  - git status
  - git diff --exit-code

script:
  # for main_test.go
  - make install

  - make test-race
  - make test-cover
  - make test-crosscover

  - make devcontainer TARGET=test-race-crosscover \
                      TEST_FLAGS='-timeout=180s -v' \
                      TEST_PACKAGES=./services/supervisord \
                      TEST_RUN_UPDATE=1

  - make check

after_success:
  - curl https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f race-crosscover.out -F devcontainer,crosscover -X fix
  - ./codecov -f cover.out -F normal,cover -X fix
  - ./codecov -f crosscover.out -F normal,crosscover -X fix

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: QDKp28RJiVnst5gGKSKhVWvyIacYFLvl4eypPQoagrUm7VlQlGdmExH841OtURbqwNNsQoai2kP1XfxxSTPtTzmp6rMsBH4D4+cAfpqE2xgP/zQ1ctbA7B4hSAGu0FkAzyhiQb6HaGIeELaTiS5uTgwHn64BNgNtf8rC3mCIUanKlpAwPOejDOvldjkL3TzNkjnv9kujLQhiSSlldMownb0gNeSiH2HfYAZ9XT5wQj6rBEGI2Mk5xBzkEduLpHMe6r8Ocko3j3q3czrNrlrqgPiTzYIh+A1h6cSGu4xe6C3WmANVbHi/ieeM3YM+pT1ff5Mx0g75Kyi18zBCSWL4tBOeu+ciHPAPKFGx7sv5ivLNzoKJm/Fc3AsdkkAvSHErsrRCWdwemRveSdbNOkwDybNSso3ERRZ8YuWIP5rdKb8HIprVuMrvlrpjXi5p901Nabt7Pw4mgDBVJIIvZn8PJ4N/0T+RGO2bV38JlWIutLFHFcHcQ2QPZOiGPffxbtfmU7x7+J4QCHhA4ucYkwzxEb7UZcGpSxz3+zVoP25c480Z56KInkxIEi0LBEqw2s7MqsKpgho4KJIpCbciDhPN7MTm4aVeYjtJ0GgIbgKXuaLWMUMcYQ0yTHUHweGMHLSF/k7cdP8WSb4z1LtJqxKzye9IcejdacVPhdLzHaprW7w=
