---
version: '3.7'
services:
  pmm-managed-server:
    image: ${PMM_SERVER_IMAGE:-perconalab/pmm-server-fb:PR-1074-9585a6d}
    container_name: pmm-managed-server
    hostname: pmm-managed-server
    environment:
      - PATH=/root/go/bin:$PATH
      - GO_VERSION=${GO_VERSION:-1.14.x}
      - TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
      - TRAVIS_PULL_REQUEST_SHA=${TRAVIS_PULL_REQUEST_SHA}
      - TRAVIS_COMMIT=${TRAVIS_COMMIT}
      - TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}
      - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
      - REVIEWDOG_GITHUB_API_TOKEN=${REVIEWDOG_GITHUB_API_TOKEN}

    # for delve
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    volumes:
      - .:/root/go/src/github.com/percona/pmm-managed
      - ./Makefile.devcontainer:/root/go/src/github.com/percona/pmm-managed/Makefile:ro
