---
version: '3'
services:
  prometheus:
    image: ${PROMETHEUS_IMAGE:-prom/prometheus:v2.2.1}
    command: [ "--config.file=/etc/prometheus/prometheus.yml",
               "--log.level=debug",
               "--storage.tsdb.path=/prometheus",
               "--web.enable-lifecycle" ]
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./testdata/prometheus:/etc/prometheus
  consul:
    image: ${CONSUL_IMAGE:-consul:0.8.5}
    ports:
      - 127.0.0.1:8500:8500
  grafana:
    image: ${GRAFANA_IMAGE:-grafana/grafana:4.6.3}
    ports:
      - 127.0.0.1:3000:3000
    environment:
      # https://github.com/Percona-Lab/pmm-submodules/blob/ec2b115bfe88b426084c576dbe69c6e3e4b50c71/build/pmm-server-docker/playbook-install.yml#L208-L222
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
  mysql:
    image: ${MYSQL_IMAGE:-percona/percona-server:5.7}
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=pmm-managed-dev
      - MYSQL_USER=pmm-managed
      - MYSQL_PASSWORD=pmm-managed
