---
version: '3.7'
services:
  pmm-managed-server:
    image: ${PMM_SERVER_IMAGE:-perconalab/pmm-server-fb:PR-782-2b261bb}
    container_name: pmm-managed-server
    hostname: pmm-managed-server
    environment:
      - PATH=/root/go/bin:$PATH
      - GO_VERSION=${GO_VERSION:-1.13.x}

    # for delve
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    volumes:
      - .:/root/go/src/github.com/percona/pmm-managed
      - ./Makefile.devcontainer:/root/go/src/github.com/percona/pmm-managed/Makefile:ro
