---
version: '3'
services:
  prometheus:
    image: ${PROMETHEUS_IMAGE:-prom/prometheus:v1.8.2}
    command: [ "-config.file=/etc/prometheus/prometheus.yml",
               "-log.level=debug",
               "-storage.local.path=/prometheus",
               "-alertmanager.url=http://alertmanager:9093" ]
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./testdata/prometheus:/etc/prometheus

  alertmanager:
    image: ${ALERTMANAGER_IMAGE:-prom/alertmanager:v0.9.1}
    command: [ "-config.file=/etc/alertmanager/alertmanager.yml",
               "-log.level=debug",
               "-storage.path=/alertmanager" ]
    ports:
      - 127.0.0.1:9093:9093
    volumes:
      - ./testdata/alertmanager:/etc/alertmanager

  consul:
    image: ${CONSUL_IMAGE:-consul:0.8.5}
    ports:
      - 127.0.0.1:8500:8500

  mysql:
    image: ${MYSQL_IMAGE:-percona/percona-server:5.7}
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=pmm-managed-dev
      - MYSQL_USER=pmm-managed
      - MYSQL_PASSWORD=pmm-managed
