---
version: '3'
services:
  prometheus:
    image: ${PROMETHEUS_IMAGE:-prom/prometheus:v2.10.0}
    command: [ "--config.file=/etc/prometheus/prometheus.yml",
               "--log.level=debug",
               "--storage.tsdb.path=/prometheus",
               "--web.enable-lifecycle",
               "--web.external-url=http://127.0.0.1:9090/prometheus/" ]
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./testdata/prometheus:/etc/prometheus

  grafana:
    image: ${GRAFANA_IMAGE:-grafana/grafana:6.2.5}
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./testdata/grafana:/etc/grafana

  postgres:
    image: ${POSTGRES_IMAGE:-postgres:10}
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_DB=pmm-managed-dev
      - POSTGRES_USER=pmm-managed
      - POSTGRES_PASSWORD=pmm-managed
