---
version: '3'
services:
  prometheus:
    image: ${PROMETHEUS_IMAGE:-prom/prometheus:v2.7.0}
    command: [ "--config.file=/etc/prometheus/prometheus.yml",
               "--log.level=debug",
               "--storage.tsdb.path=/prometheus",
               "--web.enable-lifecycle",
               "--web.external-url=http://127.0.0.1:9090/" ]
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./testdata/prometheus:/etc/prometheus

  grafana:
    image: ${GRAFANA_IMAGE:-grafana/grafana:5.1.3}
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./testdata/grafana:/etc/grafana

  mysql:
    # We use 5.5 inside pmm-server Docker container, but there is no percona/percona-server:5.5
    image: ${MYSQL_IMAGE:-percona/percona-server:5.7}
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=pmm-managed-dev
      - MYSQL_USER=pmm-managed
      - MYSQL_PASSWORD=pmm-managed

  postgres:
    image: ${POSTGRES_IMAGE:-postgres:10}
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_DB=pmm-managed-dev
      - POSTGRES_USER=pmm-managed
      - POSTGRES_PASSWORD=pmm-managed
