---
version: '3'
services:
  pmm-managed-server:
    image: ${PMM_SERVER_IMAGE:-perconalab/pmm-server:dev-latest}
    container_name: pmm-managed-server
    environment:
      - PATH=/root/go/bin:$PATH
      - GO_VERSION=${GO_VERSION:-go1.13.5}
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    volumes:
      - .:/root/go/src/github.com/percona/pmm-managed
      - ./Makefile.devcontainer:/root/go/src/github.com/percona/pmm-managed/Makefile
      # - ./testdata/prometheus/prometheus.yml:/etc/prometheus.yml
      - ./testdata/supervisord.d/prometheus.ini:/etc/supervisord.d/prometheus.ini
      - ./testdata/supervisord.d/qan-api2.ini:/etc/supervisord.d/qan-api2.ini
