---
version: '3'
services:
  pmm-managed-server:
    image: ${PMM_SERVER_IMAGE:-percona/pmm-server:2}
    container_name: pmm-managed-server
    environment:
      # for tests
      - DEVCONTAINER=1
      - PMM_SERVER_IMAGE=${PMM_SERVER_IMAGE:-percona/pmm-server:2}
      - PATH=/root/go/bin:$PATH
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    volumes:
      - .:/root/go/src/github.com/percona/pmm-managed
      - ./testdata/supervisord.d/prometheus.ini:/etc/supervisord.d/prometheus.ini
      - ./testdata/supervisord.d/qan-api2.ini:/etc/supervisord.d/qan-api2.ini

  prometheus:
    image: ${PROMETHEUS_IMAGE:-prom/prometheus:v2.12.0}
    command: [ "--config.file=/etc/prometheus/prometheus.yml",
               "--log.level=debug",
               "--storage.tsdb.path=/prometheus",
               "--web.enable-lifecycle",
               "--web.external-url=http://127.0.0.1:9090/prometheus/" ]
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./testdata/prometheus:/etc/prometheus

  grafana:
    image: ${GRAFANA_IMAGE:-grafana/grafana:6.3.3}
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./testdata/grafana:/etc/grafana

  postgres:
    image: ${POSTGRES_IMAGE:-postgres:11}
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_DB=pmm-managed-dev
      - POSTGRES_USER=pmm-managed
      - POSTGRES_PASSWORD=pmm-managed
