# tools
required = [
  "gopkg.in/reform.v1/reform",

  "github.com/prometheus/prometheus/cmd/promtool",

  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger",
  "github.com/go-swagger/go-swagger/cmd/swagger"
]

[[constraint]]
  # we do not support 2.0 yet
  name = "github.com/prometheus/prometheus"
  version = "1.8.2"

[[constraint]]
  # we need allow_delete_body
  name = "github.com/grpc-ecosystem/grpc-gateway"
  branch = "master"

[[constraint]]
  # this branch is not merged yet
  name = "github.com/percona/kardianos-service"
  branch = "PMM-1710-supervisord"
